import { describe, expect, it } from "bun:test"
import { compressToBase64 } from "lz-string"

import { parseMindMapDocument, parseSmmPage, parseSmmSections } from "../src/parser.ts"

function encodedDocument(): string {
  return compressToBase64(
    JSON.stringify({
      root: {
        data: { text: "Root" },
        children: [
          {
            data: { text: "Branch" },
            children: [],
          },
        ],
      },
      theme: {
        template: "classic13",
        config: {},
      },
      layout: "logicalStructure",
    }),
  )
}

function smmPage(): string {
  return `---
path: Demo.smm.md
tags:
  - simple-mind-map
---
> Generated by Obsidian Simple mind map
# metadata
\`\`\`metadata
${encodedDocument()}
\`\`\`
# svgdata
\`\`\`svgData
<svg></svg>
\`\`\`
# linkdata
- [[Related]]
# textdata
Root

Branch`
}

describe("parseSmmSections", () => {
  it("extracts SimpleMindMap sections when page uses Obsidian plugin format", () => {
    const sections = parseSmmSections(smmPage())

    expect(sections.metadata).toBe(encodedDocument())
    expect(sections.svgdata).toBe("<svg></svg>")
    expect(sections.linkdata).toEqual(["[[Related]]"])
    expect(sections.textdata).toContain("Branch")
  })
})

describe("parseMindMapDocument", () => {
  it("returns a typed mind map document when metadata is compressed JSON", () => {
    const result = parseMindMapDocument(encodedDocument())

    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.value.root.data.text).toBe("Root")
      expect(result.value.layout).toBe("logicalStructure")
      expect(result.value.theme.template).toBe("classic13")
    }
  })

  it("returns invalid JSON when metadata decompresses to non-JSON text", () => {
    const result = parseMindMapDocument("plain text")

    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.error.kind).toBe("invalid_json")
    }
  })
})

describe("parseSmmPage", () => {
  it("parses the current page into a renderable mind map document", () => {
    const result = parseSmmPage(smmPage())

    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.value.root.children).toHaveLength(1)
    }
  })

  it("returns missing metadata for ordinary markdown", () => {
    const result = parseSmmPage("# Ordinary note")

    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.error.kind).toBe("missing_metadata")
    }
  })

  it("parses the provided Obsidian sample page", async () => {
    const pageText = await Bun.file("../../inbox/silverbullet插件现象/test.md").text()
    const result = parseSmmPage(pageText)

    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.value.layout).toBe("logicalStructure")
      expect(result.value.theme.template).toBe("classic")
      expect(result.value.root.data.text).toBe("<p>根节点</p>")
      expect(result.value.root.children).toHaveLength(2)
    }
  })
})
